"""
The NumParamGenerator class is a subclass of ConstrainedDecoder
and handles the number parameter generation with constrained decoding.
"""


import re


from llm_sdk import Small_LLM_Model
from src.constrained_decoder import ConstrainedDecoder
from src.parse_funcs import FuncDef
from src.parse_prompts import Prompt


class NumParamGenerator(ConstrainedDecoder):
    def __init__(self, llm: Small_LLM_Model, max_tokens: int = 150) -> None:
        super().__init__(llm, max_tokens)

    def generate(self, prompt: Prompt, func_def: FuncDef,
                 var_name: str, type: str,
                 used_candidates: list[str]) -> str | None:
        """
        Extract a numeric value of a parameter from the llm genertion
        using constrained decoding.
        Allow the llm to only generate numbers that appears in the prompt.
        Stops when a match is found or reaching max_tokens or EOS.

        Switch to free generating instead if
        there are fewer arabic numbers in the prompt than parameters.
        """
        message = self.create_prompt_parameters(prompt, func_def,
                                                var_name, type)
        # Encode prompt into a 2D tensor and convert into a list
        input_ids = self.encode_cache(message)

        # Only allow numbers that appear in the prompt
        prompt_nums = self.get_valid_num(prompt.prompt)
        # Free generation of no numbers in the prompt
        if len(prompt_nums) == 0:
            return self.generate_num_param_free(input_ids,
                                                used_candidates)
        # Switch to free generating if there are fewer arabic numbers
        # in the prompt than parameters
        total_num_parameters = self.count_parameters(func_def, "number")
        if len(prompt_nums) < total_num_parameters:
            return self.generate_num_param_free(input_ids,
                                                used_candidates)

        available_can = self.get_available_candidates(prompt_nums,
                                                      used_candidates)
        # Switch to free generation
        # when available candidates have been exhausted.
        if len(available_can) == 0:
            return self.generate_num_param_free(input_ids,
                                                used_candidates)
        candidates = self.tokenize_str(available_can)

        return self.generate_constrained(input_ids, candidates)

    def generate_num_param_free(self, input_ids: list[int],
                                used_can: list[str]) -> str | None:
        """
        If there are no arabic numbers in the prompt,
        extract the first arabic number
        generated by the llm using regex.
        Wait until the matched number stops growing before returning it.
        """
        eos_ids = self.get_eos()
        # All generated tokens
        generated_ids: list[int] = []

        # Track the last matched number its length
        last_match: str = ""
        last_match_len = -1

        # Save the target number and stop re-evaluating which number to skip
        locked_target: str = ""

        # Generate one token at a time, up to max_tokens
        for _ in range(self.max_tokens):
            # Pick the best next token based on all generated token so far
            next_id, _ = self.get_next_token_id(input_ids + generated_ids,
                                                None)
            # Stop if llm generates EOS
            if next_id in eos_ids:
                return self.validate_num(last_match)

            generated_ids.append(next_id)

            res = self.llm.decode(generated_ids)
            num = self.get_valid_num(res)
            if len(num) == 0:
                continue

            # Target number not yet identified
            if len(locked_target) == 0:
                # Skip the numbers in used_candidates
                remaining_can = used_can.copy()
                target_match = ""
                for n in num:
                    if n in remaining_can:
                        remaining_can.remove(n)
                    else:
                        target_match = n
                        break
                # If all found numbers so far have been used and thus skipped
                if len(target_match) == 0:
                    continue

                # Only lock the target_match if it is not just a -
                if target_match != "-":
                    locked_target = target_match
                    last_match = locked_target
                    last_match_len = len(locked_target)

            # There is already a locked target match
            else:
                # Find match that starts with locked_target
                # and check if it still grows
                growing_match = next(
                    (n for n in num if n.startswith(locked_target) or
                     locked_target.startswith(n)),
                    None,
                )
                # Somehow no match is found
                if growing_match is None:
                    return self.validate_num(last_match)
                # Check if the number we match is still growing
                # and only return if it stops growing
                if len(growing_match) > last_match_len:
                    last_match = growing_match
                    last_match_len = len(target_match)
                    locked_target = growing_match
                # If the match is shorter than locked_target, keep generating
                elif locked_target.startswith(growing_match) \
                        and len(growing_match) < last_match_len:
                    continue
                else:
                    return last_match

        return self.validate_num(last_match)

    def get_valid_num(self, string: str) -> list[str]:
        """
        Extract all numbers strings that appear in a string
        using regex.
        """
        complete = re.findall(r"-?\d+(?:\.\d+)?", string)
        if complete:
            return complete

        # Check if the generated text so far starts with a '-'
        # Could be the model starts to generate a negative number
        if string.rstrip().endswith("-"):
            return ["-"]

        return []

    def validate_num(self, num_str: str) -> str | None:
        """
        Check if the num_str found is only a "-".
        If yes, return None instead.
        """
        if not num_str or num_str == "-" or len(num_str) == 0:
            return None
        return num_str
